# Generated by Django 5.2.6 on 2025-11-22 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        # Drop the incorrectly typed tenant_id column
        migrations.RunSQL(
            "ALTER TABLE accounts_auditlog DROP COLUMN IF EXISTS tenant_id;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Add the tenant_id column with correct UUID type
        migrations.RunSQL(
            """
            ALTER TABLE accounts_auditlog
            ADD COLUMN tenant_id uuid REFERENCES accounts_tenant(id);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Create index for the new column
        migrations.RunSQL(
            "CREATE INDEX accounts_auditlog_tenant_id_idx ON accounts_auditlog (tenant_id);",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
