# Generated by Django 5.2.6 on 2025-10-26 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_signup', 'User Signup'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('user_profile_update', 'Profile Update'), ('user_password_change', 'Password Change'), ('invitation_sent', 'Invitation Sent'), ('invitation_confirmed', 'Invitation Confirmed'), ('invitation_used', 'Invitation Used'), ('invitation_cancelled', 'Invitation Cancelled'), ('invitation_expired', 'Invitation Expired'), ('member_approved', 'Member Approved'), ('member_rejected', 'Member Rejected'), ('role_created', 'Role Created'), ('role_updated', 'Role Updated'), ('role_assigned', 'Role Assigned'), ('bulk_invitation_started', 'Bulk Invitation Started'), ('bulk_invitation_completed', 'Bulk Invitation Completed'), ('security_failed_login', 'Failed Login Attempt'), ('security_token_misuse', 'Token Misuse'), ('admin_user_suspended', 'User Suspended'), ('admin_user_activated', 'User Activated')], max_length=50)),
                ('resource_type', models.CharField(choices=[('user', 'User'), ('invitation', 'Invitation'), ('role', 'Role'), ('tenant', 'Tenant'), ('profile', 'User Profile'), ('bulk_invitation', 'Bulk Invitation')], max_length=20)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant', 'timestamp'], name='accounts_au_tenant__efb342_idx'), models.Index(fields=['user'], name='accounts_au_user_id_2e9d8e_idx'), models.Index(fields=['action'], name='accounts_au_action_5ca9a9_idx'), models.Index(fields=['resource_type', 'resource_id'], name='accounts_au_resourc_30880d_idx')],
            },
        ),
    ]
