# Generated by Django 5.2.6 on 2025-10-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_change_audit_log_resource_id_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
