# Generated by Django 5.2.6 on 2025-10-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_email_confirmed_to_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_signup', 'User Signup'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('user_profile_update', 'Profile Update'), ('user_password_change', 'Password Change'), ('invitation_sent', 'Invitation Sent'), ('invitation_confirmed', 'Invitation Confirmed'), ('invitation_used', 'Invitation Used'), ('invitation_cancelled', 'Invitation Cancelled'), ('invitation_expired', 'Invitation Expired'), ('member_approved', 'Member Approved'), ('member_rejected', 'Member Rejected'), ('role_created', 'Role Created'), ('role_updated', 'Role Updated'), ('role_assigned', 'Role Assigned'), ('project_created', 'Project Created'), ('bulk_invitation_started', 'Bulk Invitation Started'), ('bulk_invitation_completed', 'Bulk Invitation Completed'), ('security_failed_login', 'Failed Login Attempt'), ('security_token_misuse', 'Token Misuse'), ('admin_user_suspended', 'User Suspended'), ('admin_user_activated', 'User Activated')], max_length=50),
        ),
    ]
