# Generated by Django 5.2.6 on 2025-10-26 19:05

import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_auditlog_action'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP TABLE IF EXISTS accounts_invitation;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('email', models.EmailField()),
                ('tenant', models.ForeignKey(on_delete=models.CASCADE, to='accounts.tenant')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('role', models.CharField(default='Employee', max_length=100)),
                ('invited_by', models.ForeignKey(on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('email_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'accounts_invitation',
            },
        ),
    ]
