# Generated by Django 5.2.6 on 2025-10-26 19:43

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_invitation_slug_alter_invitation_id'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Drop and recreate UserTenant table with new schema
            DROP TABLE IF EXISTS accounts_usertenant;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='UserTenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=models.CASCADE, to='accounts.tenant')),
                ('is_owner', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('role', models.CharField(default='Employee', max_length=100)),
            ],
            options={
                'db_table': 'accounts_usertenant',
            },
        ),
    ]
