# Generated by Django 5.2.6 on 2025-10-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_tenant_uuid_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invitation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tenant',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usertenant',
            table=None,
        ),
    ]
