# Generated by Django 5.2.6 on 2025-10-27 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_invitation_table_alter_tenant_table_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Fix UserTenant.tenant_id column type to match Tenant.id (UUID)
            -- Drop existing foreign key constraint
            ALTER TABLE accounts_usertenant DROP CONSTRAINT IF EXISTS accounts_usertenant_tenant_id_fk;

            -- Change column type from bigint to uuid (table is empty so no data conversion needed)
            ALTER TABLE accounts_usertenant ALTER COLUMN tenant_id TYPE uuid USING (NULL::uuid);

            -- Recreate foreign key constraint
            ALTER TABLE accounts_usertenant ADD CONSTRAINT accounts_usertenant_tenant_id_fk
                FOREIGN KEY (tenant_id) REFERENCES accounts_tenant(id) ON DELETE CASCADE;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
