# Generated by Django 5.2.6 on 2025-10-27 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_invitation_table_alter_tenant_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertenant',
            name='tenant',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='accounts.tenant'
            ),
        ),
    ]
