# Generated by Django 5.2.6 on 2025-10-27 19:00

from django.db import migrations, models
import django.db.models.deletion


def alter_invitation_tenant_fk(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            "ALTER TABLE accounts_invitation ALTER COLUMN tenant_id TYPE uuid USING tenant_id::text::uuid"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_user_slug'),
    ]

    operations = [
        migrations.RunPython(
            alter_invitation_tenant_fk,
            reverse_code=migrations.RunPython.noop
        ),
    ]
