# Generated by Django 5.2.6 on 2025-11-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_fix_invitation_tenant_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='default_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('BRL', 'Brazilian Real'), ('ZAR', 'South African Rand'), ('KES', 'Kenyan Shilling')], default='USD', help_text='Default currency for invoices and payments', max_length=3),
        ),
    ]
