# Generated by Django 5.2.6 on 2025-11-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_custompermission_permissiongroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiongroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
