# Generated by Django 5.2.6 on 2025-11-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_permission_group_name_unique'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='custompermission',
            index=models.Index(fields=['created_by'], name='accounts_cu_created_559aa4_idx'),
        ),
    ]
