# Generated by Django 5.2.6 on 2025-11-13 19:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_custompermission_accounts_cu_created_559aa4_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissiongroup',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='permissiongroup',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='usertenant',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Department Manager', 'Department Manager'), ('HR Manager', 'HR Manager'), ('General Manager', 'General Manager'), ('Tenant Owner', 'Tenant Owner')], default='Employee', help_text='User role within the tenant', max_length=100),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(help_text='Department name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Department description and responsibilities')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this department is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, help_text='Department manager (typically Department Manager role)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL)),
                ('parent_department', models.ForeignKey(blank=True, help_text='Parent department for hierarchical structure', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='accounts.department')),
                ('tenant', models.ForeignKey(help_text='Company/tenant this department belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='accounts.tenant')),
            ],
            options={
                'ordering': ['tenant', 'name'],
            },
        ),
        migrations.AddField(
            model_name='usertenant',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.department'),
        ),
        migrations.RemoveField(
            model_name='permissiongroup',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='permissiongroup',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='permissiongroup',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='permissiongroup',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='permissiongroup',
            name='users',
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['tenant', 'is_active'], name='accounts_de_tenant__0c9a54_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['manager'], name='accounts_de_manager_1572ca_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['parent_department'], name='accounts_de_parent__572fdb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'tenant')},
        ),
    ]
