# Generated by Django 5.2.6 on 2025-11-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_custompermission_accounts_cu_created_559aa4_idx'),
    ]

    operations = [
        # Fix tenant_id type mismatch in AuditLog
        migrations.AlterField(
            model_name='auditlog',
            name='tenant',
            field=models.ForeignKey(
                'accounts.Tenant',
                on_delete=models.CASCADE,
                null=True,
                blank=True,
                db_index=True
            ),
        ),
    ]
