# Generated by Django 5.2.6 on 2025-11-15 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_permissiongroup_options_and_more'),
    ]

    operations = [
    ]
