# Generated by Django 5.2.6 on 2025-11-17 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_merge_20251115_1048'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='department',
            name='accounts_de_tenant__0c9a54_idx',
        ),
        migrations.RemoveIndex(
            model_name='department',
            name='accounts_de_manager_1572ca_idx',
        ),
        migrations.RemoveIndex(
            model_name='department',
            name='accounts_de_parent__572fdb_idx',
        ),
        migrations.AddField(
            model_name='usertenant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usertenant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
