# Generated by Django 5.2.6 on 2025-11-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_add_usertenant_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
