# Generated by Django 5.2.6 on 2025-11-18 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_fix_tenant_uuid_type"),
        ("accounts", "0022_add_timestamps_to_remaining_models"),
    ]

    operations = []
