# Generated by Django 5.2.6 on 2025-11-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_merge_20251118_1204"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permissiongroup",
            options={"ordering": ["tenant", "name"]},
        ),
        migrations.RemoveField(
            model_name="usertenant",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="usertenant",
            name="updated_at",
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["tenant", "is_active"], name="accounts_de_tenant__0c9a54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["manager"], name="accounts_de_manager_1572ca_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["parent_department"], name="accounts_de_parent__572fdb_idx"),
        ),
    ]
