# Generated by Django 5.2.6 on 2025-11-19 09:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_permissiongroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertenant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usertenant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
