# Generated by Django 5.2.6 on 2025-11-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0025_usertenant_created_at_usertenant_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertenant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
