# Generated by Django 5.2.6 on 2025-11-24 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0001_initial"),
        ("project", "0003_remove_payment_invoice_remove_payment_tenant_and_more"),
    ]

    operations = [
        # Data migration operations (only run if source tables exist)
        # Since this is a fresh setup, these operations are no-ops but included for completeness
        migrations.RunSQL(
            """
            -- Check if project_invoice table exists before migrating
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'project_invoice') THEN
                    INSERT INTO accounting_invoice (
                        id, slug, invoice_number, tenant_id, client_id, project_id,
                        currency, amount, tax_amount, discount_amount, status,
                        issued_at, due_date, paid_at, notes, terms, created_by_id,
                        created_at, updated_at, is_deleted, deleted_at
                    )
                    SELECT
                        id, slug, NULL as invoice_number, tenant_id, client_id, project_id,
                        currency, amount, 0 as tax_amount, 0 as discount_amount,
                        CASE WHEN paid = true THEN 'paid' ELSE 'sent' END as status,
                        issued_at, NULL as due_date,
                        CASE WHEN paid = true THEN issued_at ELSE NULL END as paid_at,
                        NULL as notes, NULL as terms, NULL as created_by_id,
                        created_at, updated_at, false as is_deleted, NULL as deleted_at
                    FROM project_invoice
                    WHERE is_deleted = false;
                END IF;
            END $$;
            """,
            reverse_sql="""
            -- Reverse migration (only if needed)
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'project_invoice') THEN
                    INSERT INTO project_invoice (
                        id, slug, tenant_id, client_id, project_id, currency, amount,
                        issued_at, paid, created_at, updated_at, is_deleted, deleted_at
                    )
                    SELECT
                        id, slug, tenant_id, client_id, project_id, currency, amount,
                        issued_at, CASE WHEN status = 'paid' THEN true ELSE false END as paid,
                        created_at, updated_at, is_deleted, deleted_at
                    FROM accounting_invoice;
                END IF;
            END $$;
            """,
        ),
        migrations.RunSQL(
            """
            -- Check if project_payment table exists before migrating
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'project_payment') THEN
                    INSERT INTO accounting_payment (
                        id, slug, payment_reference, tenant_id, invoice_id, client_id,
                        currency, amount, payment_method, paid_at, processed_at,
                        notes, transaction_id, recorded_by_id,
                        created_at, updated_at, is_deleted, deleted_at
                    )
                    SELECT
                        id, slug, NULL as payment_reference, tenant_id, invoice_id, NULL as client_id,
                        currency, amount, 'bank_transfer' as payment_method, paid_at, paid_at as processed_at,
                        NULL as notes, NULL as transaction_id, NULL as recorded_by_id,
                        created_at, updated_at, false as is_deleted, NULL as deleted_at
                    FROM project_payment
                    WHERE is_deleted = false;
                END IF;
            END $$;
            """,
            reverse_sql="""
            -- Reverse migration (only if needed)
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'project_payment') THEN
                    INSERT INTO project_payment (
                        id, slug, tenant_id, invoice_id, currency, amount,
                        paid_at, created_at, updated_at, is_deleted, deleted_at
                    )
                    SELECT
                        id, slug, tenant_id, invoice_id, currency, amount,
                        paid_at, created_at, updated_at, is_deleted, deleted_at
                    FROM accounting_payment;
                END IF;
            END $$;
            """,
        ),
        # Update payment client_id based on invoice client (only if payments exist)
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM accounting_payment WHERE invoice_id IS NOT NULL) THEN
                    UPDATE accounting_payment
                    SET client_id = accounting_invoice.client_id
                    FROM accounting_invoice
                    WHERE accounting_payment.invoice_id = accounting_invoice.id
                    AND accounting_payment.invoice_id IS NOT NULL;
                END IF;
            END $$;
            """,
            reverse_sql="""
            -- No reverse operation needed for this update
            """,
        ),
    ]
