# Generated by Django 5.2.6 on 2025-11-24 17:56

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_fix_auditlog_tenant_column_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?1?\\d{9,15}$", "Enter a valid phone number."
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prospect", "Prospect"),
                            ("qualified", "Qualified Lead"),
                            ("proposal", "Proposal Sent"),
                            ("negotiation", "In Negotiation"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                            ("inactive", "Inactive"),
                        ],
                        db_index=True,
                        default="prospect",
                        max_length=20,
                    ),
                ),
                (
                    "lead_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("website", "Website"),
                            ("referral", "Referral"),
                            ("social_media", "Social Media"),
                            ("cold_outreach", "Cold Outreach"),
                            ("trade_show", "Trade Show"),
                            ("advertising", "Advertising"),
                            ("other", "Other"),
                        ],
                        help_text="How did we acquire this lead?",
                        max_length=50,
                    ),
                ),
                (
                    "lead_score",
                    models.IntegerField(
                        default=0,
                        help_text="Lead qualification score (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("industry", models.CharField(blank=True, max_length=100)),
                (
                    "company_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1-10", "1-10 employees"),
                            ("11-50", "11-50 employees"),
                            ("51-200", "51-200 employees"),
                            ("201-1000", "201-1000 employees"),
                            ("1000+", "1000+ employees"),
                        ],
                        max_length=20,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("address", models.TextField(blank=True)),
                ("primary_contact", models.CharField(blank=True, max_length=255)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                (
                    "estimated_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Estimated deal value",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar ($)"),
                            ("EUR", "Euro (€)"),
                            ("GBP", "British Pound (£)"),
                            ("JPY", "Japanese Yen (¥)"),
                            ("CAD", "Canadian Dollar (C$)"),
                            ("AUD", "Australian Dollar (A$)"),
                            ("CHF", "Swiss Franc (CHF)"),
                            ("CNY", "Chinese Yuan (¥)"),
                            ("INR", "Indian Rupee (₹)"),
                            ("BRL", "Brazilian Real (R$)"),
                            ("ZAR", "South African Rand (R)"),
                            ("KES", "Kenyan Shilling (KSh)"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("expected_close_date", models.DateField(blank=True, null=True)),
                ("actual_close_date", models.DateField(blank=True, null=True)),
                ("last_contact", models.DateTimeField(blank=True, null=True)),
                ("next_followup", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sales_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_customers",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar ($)"),
                            ("EUR", "Euro (€)"),
                            ("GBP", "British Pound (£)"),
                            ("JPY", "Japanese Yen (¥)"),
                            ("CAD", "Canadian Dollar (C$)"),
                            ("AUD", "Australian Dollar (A$)"),
                            ("CHF", "Swiss Franc (CHF)"),
                            ("CNY", "Chinese Yuan (¥)"),
                            ("INR", "Indian Rupee (₹)"),
                            ("BRL", "Brazilian Real (R$)"),
                            ("ZAR", "South African Rand (R)"),
                            ("KES", "Kenyan Shilling (KSh)"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "probability",
                    models.IntegerField(
                        default=0,
                        help_text="Win probability percentage (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("prospecting", "Prospecting"),
                            ("qualification", "Qualification"),
                            ("proposal", "Proposal"),
                            ("negotiation", "Negotiation"),
                            ("closed_won", "Closed Won"),
                            ("closed_lost", "Closed Lost"),
                        ],
                        db_index=True,
                        default="prospecting",
                        max_length=20,
                    ),
                ),
                ("expected_close_date", models.DateField(blank=True, null=True)),
                ("actual_close_date", models.DateField(blank=True, null=True)),
                ("competitors", models.TextField(blank=True)),
                ("competitive_advantage", models.TextField(blank=True)),
                ("requirements", models.TextField(blank=True)),
                ("pain_points", models.TextField(blank=True)),
                ("next_steps", models.TextField(blank=True)),
                ("next_followup", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_opportunities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_opportunities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="sales.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("call", "Phone Call"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                            ("demo", "Product Demo"),
                            ("proposal", "Proposal Sent"),
                            ("followup", "Follow-up"),
                            ("negotiation", "Negotiation"),
                            ("note", "Internal Note"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("scheduled_date", models.DateTimeField(blank=True, null=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                ("outcome", models.TextField(blank=True)),
                ("next_action", models.TextField(blank=True)),
                ("next_action_date", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="sales.customer",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="sales.opportunity",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_activities",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_date", "-scheduled_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesTeam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("territory", models.CharField(blank=True, max_length=100)),
                (
                    "target_quota",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar ($)"),
                            ("EUR", "Euro (€)"),
                            ("GBP", "British Pound (£)"),
                            ("JPY", "Japanese Yen (¥)"),
                            ("CAD", "Canadian Dollar (C$)"),
                            ("AUD", "Australian Dollar (A$)"),
                            ("CHF", "Swiss Franc (CHF)"),
                            ("CNY", "Chinese Yuan (¥)"),
                            ("INR", "Indian Rupee (₹)"),
                            ("BRL", "Brazilian Real (R$)"),
                            ("ZAR", "South African Rand (R)"),
                            ("KES", "Kenyan Shilling (KSh)"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "current_quota_progress",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_sales_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True, related_name="sales_teams", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_teams",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["tenant", "status"], name="sales_custo_tenant__1d22d2_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["assigned_to", "status"], name="sales_custo_assigne_644e0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["lead_score"], name="sales_custo_lead_sc_11d14a_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["expected_close_date"], name="sales_custo_expecte_534326_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["slug"], name="sales_custo_slug_ba59a6_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["created_at"], name="sales_custo_created_3625af_idx"),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(fields=["tenant", "stage"], name="sales_oppor_tenant__b2ea1e_idx"),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(fields=["customer", "stage"], name="sales_oppor_custome_f5b17f_idx"),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["assigned_to", "stage"], name="sales_oppor_assigne_7a9c88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["expected_close_date"], name="sales_oppor_expecte_dc184c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(fields=["probability"], name="sales_oppor_probabi_9732d5_idx"),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(fields=["slug"], name="sales_oppor_slug_b4cf8f_idx"),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(fields=["created_at"], name="sales_oppor_created_dfec50_idx"),
        ),
        migrations.AddIndex(
            model_name="salesactivity",
            index=models.Index(
                fields=["tenant", "activity_type"], name="sales_sales_tenant__d884ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesactivity",
            index=models.Index(
                fields=["customer", "activity_type"], name="sales_sales_custome_e481d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesactivity",
            index=models.Index(
                fields=["opportunity", "activity_type"], name="sales_sales_opportu_224fa5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesactivity",
            index=models.Index(
                fields=["performed_by", "activity_type"], name="sales_sales_perform_9c728b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesactivity",
            index=models.Index(fields=["scheduled_date"], name="sales_sales_schedul_894278_idx"),
        ),
        migrations.AddIndex(
            model_name="salesactivity",
            index=models.Index(fields=["completed_date"], name="sales_sales_complet_4b4a53_idx"),
        ),
        migrations.AddIndex(
            model_name="salesactivity",
            index=models.Index(fields=["created_at"], name="sales_sales_created_d0c94e_idx"),
        ),
        migrations.AddIndex(
            model_name="salesteam",
            index=models.Index(
                fields=["tenant", "is_active"], name="sales_sales_tenant__060abb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesteam",
            index=models.Index(fields=["manager"], name="sales_sales_manager_d12e04_idx"),
        ),
        migrations.AddIndex(
            model_name="salesteam",
            index=models.Index(fields=["territory"], name="sales_sales_territo_f530ca_idx"),
        ),
    ]
