
services:
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: your-dockerhub-username/saascrm-backend:latest
    restart: always
     environment:
       - DJANGO_ENV=production
       - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
       - SECRET_KEY=${SECRET_KEY}
       - RUN_SETUP=false
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_prod:/app/static
    ports:
      - "8000:8000"

  frontend:
    image: your-dockerhub-username/saascrm-frontend:latest
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.yourdomain.com
    command: npm run start
    ports:
      - "80:3000"

volumes:
  static_prod:
  db_data:
