# Generated by Django 5.2.6 on 2025-11-21 08:18

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveApprovalWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for the workflow (e.g., 'Standard Approval', 'Executive Approval')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of when to use this workflow"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default workflow for the tenant",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this workflow is available for use"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this workflow",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_leave_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this workflow belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_approval_workflows",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LeaveApprovalStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="Order of this step in the workflow (1, 2, 3...)"
                    ),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("user", "Specific User"),
                            ("permission_group", "Permission Group"),
                            ("role", "By Role"),
                            ("department_manager", "Employee's Department Manager"),
                            ("dynamic_hr", "Dynamic HR Selection"),
                            ("dynamic_gm", "Dynamic General Manager Selection"),
                        ],
                        help_text="How approvers are determined for this step",
                        max_length=20,
                    ),
                ),
                (
                    "required_role",
                    models.CharField(
                        blank=True,
                        help_text="Required user role for approval (for 'role' type)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "max_approvers",
                    models.IntegerField(
                        default=1,
                        help_text="Maximum number of approvers to select (prevents duplicates)",
                    ),
                ),
                (
                    "selection_criteria",
                    models.CharField(
                        choices=[
                            ("first", "First by seniority"),
                            ("random", "Random selection"),
                            ("round_robin", "Round robin"),
                        ],
                        default="first",
                        help_text="How to select approvers when multiple are eligible",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this approval step", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of this approval step"
                    ),
                ),
                (
                    "requires_notes",
                    models.BooleanField(
                        default=False,
                        help_text="Whether approvers must provide notes for this step",
                    ),
                ),
                (
                    "min_days_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum leave days required to trigger this step",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "leave_types",
                    models.JSONField(
                        default=list,
                        help_text="Specific leave types this step applies to (empty = all types)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "permission_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Permission group whose members can approve (for 'permission_group' type)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_approval_steps",
                        to="accounts.permissiongroup",
                    ),
                ),
                (
                    "specific_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific user who must approve (for 'user' type)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_approval_steps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        help_text="Workflow this step belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="leave_management.leaveapprovalworkflow",
                    ),
                ),
            ],
            options={
                "ordering": ["workflow", "order"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalLevelConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("level", models.IntegerField(help_text="Approval level number (1, 2, 3...)")),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("user", "Specific User"),
                            ("permission_group", "Permission Group"),
                            ("role", "By Role"),
                            ("department_manager", "Employee's Department Manager"),
                            ("dynamic_hr", "Dynamic HR Selection"),
                            ("dynamic_gm", "Dynamic General Manager Selection"),
                        ],
                        help_text="How approvers are determined for this level",
                        max_length=20,
                    ),
                ),
                (
                    "required_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Employee", "Employee"),
                            ("Department Manager", "Department Manager"),
                            ("HR Manager", "HR Manager"),
                            ("General Manager", "General Manager"),
                            ("Tenant Owner", "Tenant Owner"),
                        ],
                        help_text="Required user role for approval (for 'role' type)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "permission_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Permission group whose members can approve (for 'permission_group' type)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_level_configs",
                        to="accounts.permissiongroup",
                    ),
                ),
                (
                    "specific_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific user who must approve (for 'user' type)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_level_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        help_text="Workflow this config belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="level_configs",
                        to="leave_management.leaveapprovalworkflow",
                    ),
                ),
            ],
            options={
                "ordering": ["workflow", "level"],
            },
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual_leave", "Annual Leave"),
                            ("sick_leave", "Sick Leave"),
                            ("personal_leave", "Personal Leave"),
                            ("maternity_leave", "Maternity/Paternity Leave"),
                            ("emergency_leave", "Emergency Leave"),
                            ("unpaid_leave", "Unpaid Leave"),
                        ],
                        help_text="Type of leave this balance applies to",
                        max_length=20,
                    ),
                ),
                ("year", models.IntegerField(help_text="Calendar year for this leave balance")),
                (
                    "total_days",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Total leave days allocated for this year",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "used_days",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        help_text="Days already used this year",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "carried_over",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        help_text="Days carried over from previous year",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee whose leave balance this represents",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Company/tenant the balance belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "leave_type"],
            },
        ),
        migrations.CreateModel(
            name="LeavePolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual_leave", "Annual Leave"),
                            ("sick_leave", "Sick Leave"),
                            ("personal_leave", "Personal Leave"),
                            ("maternity_leave", "Maternity/Paternity Leave"),
                            ("emergency_leave", "Emergency Leave"),
                            ("unpaid_leave", "Unpaid Leave"),
                        ],
                        help_text="Type of leave this policy applies to",
                        max_length=20,
                    ),
                ),
                (
                    "annual_entitlement",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Default annual leave entitlement in days",
                        max_digits=4,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "max_consecutive_days",
                    models.IntegerField(
                        default=30,
                        help_text="Maximum consecutive days allowed for this leave type",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                    ),
                ),
                (
                    "notice_period_days",
                    models.IntegerField(
                        default=7,
                        help_text="Minimum notice period required in working days",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "carry_over_allowed",
                    models.BooleanField(
                        default=True,
                        help_text="Whether unused leave can be carried over to next year",
                    ),
                ),
                (
                    "max_carry_over",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Maximum days that can be carried over (null = unlimited)",
                        max_digits=4,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "auto_approve_max_days",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Maximum days that can be auto-approved (null = no auto-approval)",
                        max_digits=3,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this policy is currently active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval_workflow",
                    models.ForeignKey(
                        blank=True,
                        help_text="Custom approval workflow for this leave type (null = use default workflow)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leave_policies",
                        to="leave_management.leaveapprovalworkflow",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Company/tenant this policy applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_policies",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["leave_type"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual_leave", "Annual Leave"),
                            ("sick_leave", "Sick Leave"),
                            ("personal_leave", "Personal Leave"),
                            ("maternity_leave", "Maternity/Paternity Leave"),
                            ("emergency_leave", "Emergency Leave"),
                            ("unpaid_leave", "Unpaid Leave"),
                        ],
                        help_text="Type of leave being requested",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(help_text="First day of leave")),
                ("end_date", models.DateField(help_text="Last day of leave")),
                (
                    "days_requested",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Total number of leave days requested",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.5")),
                            django.core.validators.MaxValueValidator(Decimal("365")),
                        ],
                    ),
                ),
                ("reason", models.TextField(blank=True, help_text="Reason for the leave request")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_department_manager", "Pending Department Manager"),
                            ("pending_hr_manager", "Pending HR Manager"),
                            ("pending_general_manager", "Pending General Manager"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("taken", "Leave Taken"),
                        ],
                        db_index=True,
                        default="pending_department_manager",
                        help_text="Current status of leave request",
                        max_length=30,
                    ),
                ),
                (
                    "applied_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the leave request was submitted"
                    ),
                ),
                (
                    "approved_date",
                    models.DateTimeField(
                        blank=True, help_text="When the request was approved/rejected", null=True
                    ),
                ),
                ("approval_notes", models.TextField(blank=True, help_text="Notes from approver")),
                (
                    "current_approval_level",
                    models.CharField(
                        choices=[
                            ("department_manager", "Department Manager"),
                            ("hr_manager", "HR Manager"),
                            ("general_manager", "General Manager"),
                        ],
                        default="department_manager",
                        help_text="Current approval level in workflow",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Manager who approved/rejected the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee requesting leave",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "final_approver",
                    models.ForeignKey(
                        blank=True,
                        help_text="Final approver who completed the workflow",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="final_approved_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Company/tenant the request belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_date"],
            },
        ),
        migrations.CreateModel(
            name="LeaveApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                (
                    "approval_level",
                    models.CharField(
                        choices=[
                            ("department_manager", "Department Manager"),
                            ("hr_manager", "HR Manager"),
                            ("general_manager", "General Manager"),
                        ],
                        help_text="Approval level in the workflow",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Status of this approval step",
                        max_length=20,
                    ),
                ),
                (
                    "approved_date",
                    models.DateTimeField(
                        blank=True, help_text="When this approval step was completed", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Notes or comments from approver"),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="Order in approval sequence (1=first, 2=second, 3=final)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver",
                    models.ForeignKey(
                        help_text="User who performed this approval step",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_request",
                    models.ForeignKey(
                        help_text="Leave request being approved",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="leave_management.leaverequest",
                    ),
                ),
            ],
            options={
                "ordering": ["leave_request", "order"],
            },
        ),
        migrations.AddIndex(
            model_name="leaveapprovalworkflow",
            index=models.Index(
                fields=["tenant", "is_default"], name="leave_manag_tenant__59c892_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaveapprovalworkflow",
            index=models.Index(
                fields=["tenant", "is_active"], name="leave_manag_tenant__3c8f50_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leaveapprovalworkflow",
            unique_together={("tenant", "name")},
        ),
        migrations.AddIndex(
            model_name="leaveapprovalstep",
            index=models.Index(fields=["workflow", "order"], name="leave_manag_workflo_ca7055_idx"),
        ),
        migrations.AddIndex(
            model_name="leaveapprovalstep",
            index=models.Index(fields=["approval_type"], name="leave_manag_approva_8c08a6_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="leaveapprovalstep",
            unique_together={("workflow", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="approvallevelconfig",
            unique_together={("workflow", "level")},
        ),
        migrations.AddIndex(
            model_name="leavebalance",
            index=models.Index(fields=["tenant", "year"], name="leave_manag_tenant__13d2d9_idx"),
        ),
        migrations.AddIndex(
            model_name="leavebalance",
            index=models.Index(fields=["employee", "year"], name="leave_manag_employe_f70801_idx"),
        ),
        migrations.AddConstraint(
            model_name="leavebalance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "used_days__lte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("total_days"), "+", models.F("carried_over")
                        ),
                    )
                ),
                name="leave_balance_used_within_total",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leavebalance",
            unique_together={("employee", "leave_type", "year")},
        ),
        migrations.AddIndex(
            model_name="leavepolicy",
            index=models.Index(
                fields=["tenant", "is_active"], name="leave_manag_tenant__6a83c6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leavepolicy",
            unique_together={("tenant", "leave_type")},
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(fields=["tenant", "status"], name="leave_manag_tenant__ced5b4_idx"),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["employee", "status"], name="leave_manag_employe_76bff2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["start_date", "end_date"], name="leave_manag_start_d_903b4d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="leaverequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_date__lte", models.F("end_date"))),
                name="leave_request_start_before_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="leaverequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("days_requested__gt", 0)), name="leave_request_positive_days"
            ),
        ),
        migrations.AddIndex(
            model_name="leaveapproval",
            index=models.Index(
                fields=["leave_request", "status"], name="leave_manag_leave_r_3b480f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaveapproval",
            index=models.Index(fields=["approver"], name="leave_manag_approve_32cdc1_idx"),
        ),
        migrations.AddIndex(
            model_name="leaveapproval",
            index=models.Index(
                fields=["approval_level", "status"], name="leave_manag_approva_36bf34_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leaveapproval",
            unique_together={("leave_request", "approval_level")},
        ),
    ]
