# Generated by Django 5.2.6 on 2025-11-21 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("leave_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaverequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="leaverequest",
            name="leave_manag_employe_76bff2_idx",
        ),
        migrations.RemoveIndex(
            model_name="leaverequest",
            name="leave_manag_start_d_903b4d_idx",
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(fields=["employee"], name="leave_manag_employe_2d3a64_idx"),
        ),
    ]
