# Generated by Django 5.2.6 on 2025-11-21 20:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leave_management", "0002_alter_leaverequest_options_and_more"),
    ]

    operations = [
        # Drop existing tables
        migrations.RunSQL(
            "DROP TABLE IF EXISTS leave_management_approvallevelconfig CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS leave_management_leaveapprovalstep CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS leave_management_leaveapprovalworkflow CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Recreate LeaveApprovalWorkflow with correct UUID primary key
        migrations.RunSQL(
            """
            CREATE TABLE leave_management_leaveapprovalworkflow (
                id uuid NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
                name varchar(100) NOT NULL,
                description text,
                is_default bool NOT NULL,
                is_active bool NOT NULL,
                slug varchar(255),
                created_at timestamptz NOT NULL,
                updated_at timestamptz NOT NULL,
                created_by_id bigint,
                tenant_id uuid NOT NULL
            );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Recreate ApprovalLevelConfig with correct UUID foreign key
        migrations.RunSQL(
            """
            CREATE TABLE leave_management_approvallevelconfig (
                id uuid NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
                level integer NOT NULL,
                approval_type varchar(20) NOT NULL,
                required_role varchar(50),
                permission_group_id uuid,
                specific_user_id bigint,
                workflow_id uuid NOT NULL
            );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Recreate LeaveApprovalStep
        migrations.RunSQL(
            """
            CREATE TABLE leave_management_leaveapprovalstep (
                id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "order" integer NOT NULL,
                approval_type varchar(20) NOT NULL,
                required_role varchar(50),
                max_approvers integer NOT NULL,
                selection_criteria varchar(20) NOT NULL,
                name varchar(100) NOT NULL,
                description text,
                requires_notes bool NOT NULL,
                min_days_threshold numeric(5,2),
                leave_types jsonb NOT NULL,
                created_at timestamptz NOT NULL,
                updated_at timestamptz NOT NULL,
                permission_group_id uuid,
                specific_user_id bigint,
                workflow_id uuid NOT NULL
            );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Add foreign key constraints
        migrations.RunSQL(
            """
            ALTER TABLE leave_management_leaveapprovalworkflow
            ADD CONSTRAINT leave_manag_created_b_8b8f8f_fk_accounts_
            FOREIGN KEY (created_by_id) REFERENCES accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            ALTER TABLE leave_management_leaveapprovalworkflow
            ADD CONSTRAINT leave_manag_tenant_i_59c892_fk_accounts_
            FOREIGN KEY (tenant_id) REFERENCES accounts_tenant(id) DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            ALTER TABLE leave_management_approvallevelconfig
            ADD CONSTRAINT leave_manag_permissi_123456_fk_accounts_
            FOREIGN KEY (permission_group_id) REFERENCES accounts_permissiongroup(id) DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            ALTER TABLE leave_management_approvallevelconfig
            ADD CONSTRAINT leave_manag_specific_123456_fk_accounts_
            FOREIGN KEY (specific_user_id) REFERENCES accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            ALTER TABLE leave_management_approvallevelconfig
            ADD CONSTRAINT leave_manag_workflow_123456_fk_leave_ma
            FOREIGN KEY (workflow_id) REFERENCES leave_management_leaveapprovalworkflow(id) DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            ALTER TABLE leave_management_leaveapprovalstep
            ADD CONSTRAINT leave_manag_permissi_654321_fk_accounts_
            FOREIGN KEY (permission_group_id) REFERENCES accounts_permissiongroup(id) DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            ALTER TABLE leave_management_leaveapprovalstep
            ADD CONSTRAINT leave_manag_specific_654321_fk_accounts_
            FOREIGN KEY (specific_user_id) REFERENCES accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            ALTER TABLE leave_management_leaveapprovalstep
            ADD CONSTRAINT leave_manag_workflow_654321_fk_leave_ma
            FOREIGN KEY (workflow_id) REFERENCES leave_management_leaveapprovalworkflow(id) DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Add indexes
        migrations.RunSQL(
            """
            CREATE INDEX leave_manag_tenant__59c892_idx ON leave_management_leaveapprovalworkflow (tenant_id, is_default);
            CREATE INDEX leave_manag_tenant__3c8f50_idx ON leave_management_leaveapprovalworkflow (tenant_id, is_active);
            CREATE UNIQUE INDEX leave_manag_tenant__name_123456_uniq ON leave_management_leaveapprovalworkflow (tenant_id, name);
            CREATE INDEX leave_manag_workflo_ca7055_idx ON leave_management_leaveapprovalstep (workflow_id, "order");
            CREATE INDEX leave_manag_approva_8c08a6_idx ON leave_management_leaveapprovalstep (approval_type);
            CREATE UNIQUE INDEX leave_manag_workflo_order_123456_uniq ON leave_management_leaveapprovalstep (workflow_id, "order");
            CREATE UNIQUE INDEX leave_manag_workflo_level_123456_uniq ON leave_management_approvallevelconfig (workflow_id, level);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
