# Generated by Django 5.2.6 on 2025-11-21 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leave_management", "0003_fix_uuid_schema"),
    ]

    operations = [
        # Fix LeavePolicy.approval_workflow_id to use uuid
        migrations.RunSQL(
            "ALTER TABLE leave_management_leavepolicy ALTER COLUMN approval_workflow_id TYPE uuid USING approval_workflow_id::text::uuid;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
