# Generated by Django 5.2.6 on 2025-11-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leave_management", "0005_remove_complex_workflow_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaveapprovalworkflow",
            name="approval_levels",
            field=models.CharField(
                choices=[
                    ("department_manager", "Department Manager Only"),
                    ("department_manager,hr_manager", "Department Manager → HR Manager"),
                    (
                        "department_manager,hr_manager,general_manager",
                        "Department Manager → HR Manager → General Manager",
                    ),
                    ("hr_manager", "HR Manager Only"),
                    ("hr_manager,general_manager", "HR Manager → General Manager"),
                    ("general_manager", "General Manager Only"),
                ],
                default="department_manager",
                help_text="The sequence of approval levels required",
                max_length=100,
            ),
        ),
    ]
