# Generated by Django 5.2.6 on 2025-11-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leave_management", "0007_add_custom_approvers_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaverequest",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="leaverequest",
            name="leave_request_start_before_end",
        ),
        migrations.RemoveConstraint(
            model_name="leaverequest",
            name="leave_request_positive_days",
        ),
        migrations.RemoveIndex(
            model_name="leaverequest",
            name="leave_manag_tenant__ced5b4_idx",
        ),
        migrations.RemoveIndex(
            model_name="leaverequest",
            name="leave_manag_employe_2d3a64_idx",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="approval_notes",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="approved_date",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="final_approver",
        ),
        migrations.AlterField(
            model_name="leaveapprovalworkflow",
            name="custom_approvers",
            field=models.JSONField(
                blank=True,
                help_text="Custom approver configuration for 'custom' approval type",
                null=True,
            ),
        ),
    ]
