# Generated by Django 5.2.6 on 2025-11-23 12:59

import django.core.validators
from django.conf import settings
from django.db import migrations, models

import leave_management.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_fix_auditlog_tenant_column_type"),
        ("leave_management", "0008_alter_leaverequest_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaverequest",
            options={"ordering": ["-applied_date"]},
        ),
        migrations.RemoveField(
            model_name="leaveapprovalworkflow",
            name="custom_approvers",
        ),
        migrations.AddField(
            model_name="leaveapprovalworkflow",
            name="default_hr_levels",
            field=models.IntegerField(
                default=1,
                help_text="Default number of approval levels for HR (1-5)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="leavepolicy",
            name="approval_levels",
            field=models.JSONField(
                default=list,
                help_text="Configured approval levels for this policy (max 5 levels)",
                validators=[leave_management.models.validate_approval_levels],
            ),
        ),
        migrations.AlterField(
            model_name="leaveapprovalworkflow",
            name="approval_levels",
            field=models.JSONField(
                default=list,
                help_text="List of approval levels required (max 5 levels)",
                validators=[leave_management.models.validate_approval_levels],
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["employee", "status"], name="leave_manag_employe_76bff2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(fields=["tenant", "status"], name="leave_manag_tenant__ced5b4_idx"),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["start_date", "end_date"], name="leave_manag_start_d_903b4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["status", "current_approval_level"], name="leave_manag_status_4e468a_idx"
            ),
        ),
    ]
