# Generated by Django 5.2.6 on 2025-11-24 11:27

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_fix_auditlog_tenant_column_type"),
        ("leave_management", "0009_alter_leaverequest_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveSale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual_leave", "Annual Leave"),
                            ("sick_leave", "Sick Leave"),
                            ("personal_leave", "Personal Leave"),
                            ("maternity_leave", "Maternity/Paternity Leave"),
                            ("emergency_leave", "Emergency Leave"),
                            ("unpaid_leave", "Unpaid Leave"),
                        ],
                        help_text="Type of leave being sold",
                        max_length=20,
                    ),
                ),
                (
                    "days_to_sell",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Number of leave days to sell",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.5")),
                            django.core.validators.MaxValueValidator(Decimal("365")),
                        ],
                    ),
                ),
                (
                    "sale_price_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Sale price per day in company currency",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "total_sale_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total sale amount (calculated as days_to_sell * sale_price_per_day)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current status of the leave sale request",
                        max_length=20,
                    ),
                ),
                (
                    "approved_date",
                    models.DateTimeField(
                        blank=True, help_text="When the sale was approved", null=True
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, help_text="Reason for rejection if applicable"),
                ),
                (
                    "applied_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the sale request was submitted"
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Employee's reason for selling leave"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who approved this sale",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leave_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee selling leave days",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Company/tenant the sale belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_sales",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_date"],
                "indexes": [
                    models.Index(
                        fields=["employee", "status"], name="leave_manag_employe_277863_idx"
                    ),
                    models.Index(
                        fields=["tenant", "status"], name="leave_manag_tenant__0b98c1_idx"
                    ),
                    models.Index(
                        fields=["status", "applied_date"], name="leave_manag_status_4078e6_idx"
                    ),
                ],
            },
        ),
    ]
