# Generated by Django 5.2.6 on 2025-11-24 11:40

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leave_management", "0010_add_leave_sale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavesale",
            name="sale_price_per_day",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Sale price per day in company currency (set by HR during approval)",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
