# Generated by Django 5.2.6 on 2025-11-24 17:05

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_fix_auditlog_tenant_column_type"),
        ("project", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="account_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="client",
            name="billing_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="client",
            name="company_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1-10", "1-10 employees"),
                    ("11-50", "11-50 employees"),
                    ("51-200", "51-200 employees"),
                    ("201-1000", "201-1000 employees"),
                    ("1000+", "1000+ employees"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="credit_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="industry",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="client",
            name="last_contact",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="lead_score",
            field=models.IntegerField(
                default=0,
                help_text="Lead qualification score (0-100)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="lead_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("website", "Website"),
                    ("referral", "Referral"),
                    ("social_media", "Social Media"),
                    ("cold_outreach", "Cold Outreach"),
                    ("trade_show", "Trade Show"),
                    ("other", "Other"),
                ],
                help_text="How did we acquire this client?",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="next_followup",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="client",
            name="payment_terms",
            field=models.CharField(
                choices=[
                    ("immediate", "Immediate"),
                    ("net_15", "Net 15"),
                    ("net_30", "Net 30"),
                    ("net_45", "Net 45"),
                    ("net_60", "Net 60"),
                    ("custom", "Custom"),
                ],
                default="net_30",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="primary_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="satisfaction_score",
            field=models.IntegerField(
                blank=True,
                help_text="Client satisfaction rating (1-5)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="tax_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="client",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="actual_hours",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("0.0"),
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="auto_complete_on_invoice_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="client_feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="estimated_hours",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("0.0"),
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="notify_on_phase_change",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="project",
            name="phase",
            field=models.CharField(
                choices=[
                    ("initiation", "Initiation"),
                    ("planning", "Planning"),
                    ("execution", "Execution"),
                    ("monitoring", "Monitoring & Control"),
                    ("closure", "Closure"),
                ],
                default="initiation",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="quality_score",
            field=models.IntegerField(
                blank=True,
                help_text="Project quality rating (1-5)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="risk_level",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="low",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ("contract_number", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar ($)"),
                            ("EUR", "Euro (€)"),
                            ("GBP", "British Pound (£)"),
                            ("JPY", "Japanese Yen (¥)"),
                            ("CAD", "Canadian Dollar (C$)"),
                            ("AUD", "Australian Dollar (A$)"),
                            ("CHF", "Swiss Franc (CHF)"),
                            ("CNY", "Chinese Yuan (¥)"),
                            ("INR", "Indian Rupee (₹)"),
                            ("BRL", "Brazilian Real (R$)"),
                            ("ZAR", "South African Rand (R)"),
                            ("KES", "Kenyan Shilling (KSh)"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "payment_schedule",
                    models.JSONField(default=dict, help_text="Payment milestones and amounts"),
                ),
                ("issued_date", models.DateField()),
                ("signed_date", models.DateField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("contract_file", models.FileField(blank=True, null=True, upload_to="contracts/")),
                (
                    "signed_contract_file",
                    models.FileField(blank=True, null=True, upload_to="contracts/signed/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent to Client"),
                            ("signed", "Signed"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="project.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_link",
                        to="project.project",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="contract",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_link",
                to="project.contract",
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(fields=["tenant", "status"], name="project_con_tenant__bee01a_idx"),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(fields=["client", "status"], name="project_con_client__df02e5_idx"),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(fields=["contract_number"], name="project_con_contrac_9c520c_idx"),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(fields=["created_at"], name="project_con_created_10432d_idx"),
        ),
    ]
