# Generated by Django 5.2.6 on 2025-10-26 11:33

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Client = apps.get_model('project', 'Client')
    Project = apps.get_model('project', 'Project')

    # Populate slugs for clients
    for client in Client.objects.filter(slug__isnull=True):
        slug = slugify(client.name)
        if slug:
            original_slug = slug
            counter = 1
            while Client.objects.filter(slug=slug).exists():
                slug = f"{original_slug}-{counter}"
                counter += 1
            client.slug = slug
            client.save(update_fields=['slug'])

    # Populate slugs for projects
    for project in Project.objects.filter(slug__isnull=True):
        slug = slugify(project.name)
        if slug:
            original_slug = slug
            counter = 1
            while Project.objects.filter(slug=slug).exists():
                slug = f"{original_slug}-{counter}"
                counter += 1
            project.slug = slug
            project.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_client_slug_project_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs),
    ]
