# Generated by Django 5.2.6 on 2025-11-24 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_enhance_client_lifecycle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="tenant",
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
