# Generated by Django 5.2.6 on 2025-10-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_milestone_slug_sprint_slug_task_slug'),
        ('project', '0005_invoice_slug'),
    ]

    operations = [
    ]
