# Generated by Django 5.2.6 on 2025-10-27 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_merge_20251027_2031'),
        ('accounts', '0009_alter_invitation_table_alter_tenant_table_and_more'),
    ]

    operations = [
        # Alter tenant fields to use proper UUID foreign keys
        migrations.AlterField(
            model_name='client',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='clients',
                to='accounts.tenant',
                db_index=True
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='projects',
                to='accounts.tenant',
                db_index=True
            ),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='milestones',
                to='accounts.tenant',
                db_index=True
            ),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sprints',
                to='accounts.tenant',
                db_index=True
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tasks',
                to='accounts.tenant',
                db_index=True
            ),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='invoices',
                to='accounts.tenant',
                db_index=True
            ),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='payments',
                to='accounts.tenant',
                db_index=True
            ),
        ),
    ]
