# Generated by Django 5.2.6 on 2025-11-03 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_fix_invitation_tenant_fk'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('project', '0007_fix_tenant_fk_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('name', 'tenant'), name='unique_client_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('name', 'client', 'tenant'), name='unique_project_name_per_client_tenant'),
        ),
    ]
