# Generated by Django 5.2.6 on 2025-11-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_client_unique_client_name_per_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('BRL', 'Brazilian Real'), ('ZAR', 'South African Rand'), ('KES', 'Kenyan Shilling')], default='USD', help_text='Currency for this invoice', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('BRL', 'Brazilian Real'), ('ZAR', 'South African Rand'), ('KES', 'Kenyan Shilling')], default='USD', help_text='Currency for this payment', max_length=3),
        ),
    ]
