# Generated by Django 5.2.6 on 2025-11-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_invoice_currency_payment_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('BRL', 'Brazilian Real'), ('ZAR', 'South African Rand'), ('KES', 'Kenyan Shilling')], help_text='Currency for this invoice', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('BRL', 'Brazilian Real'), ('ZAR', 'South African Rand'), ('KES', 'Kenyan Shilling')], help_text='Currency for this payment', max_length=3, null=True),
        ),
    ]
