# Generated by Django 5.2.6 on 2025-11-17 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_merge_20251115_1048'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('project', '0012_alter_invoice_project_alter_milestone_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='client_tenant_status_created'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='milestone_t_status_created'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['project', 'status'], name='milestone_project_status'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='project_tenant_status_created'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tenant', 'client', 'status'], name='project_tenant_client_status'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='sprint_tenant_status_created'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['milestone', 'status'], name='sprint_milestone_status'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='task_tenant_status_created'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant', 'assignee', 'status'], name='task_tenant_assignee_status'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['milestone', 'status'], name='task_milestone_status'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['sprint', 'status'], name='task_sprint_status'),
        ),
    ]
