# Generated by Django 5.2.6 on 2025-11-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_add_performance_indexes'),
        ('project', '0013_add_performance_indexes'),
    ]

    operations = [
    ]
