# Generated by Django 5.2.6 on 2026-03-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_project_updated_at'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='project',
                    name='actual_hours',
                    field=models.PositiveIntegerField(default=0),
                ),
            ],
        ),
    ]
