# Generated by Django 5.2.6 on 2026-03-12 07:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_project_actual_hours'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='project',
                    name='auto_complete_on_invoice_paid',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='project',
                    name='client_feedback',
                    field=models.TextField(blank=True, default=''),
                ),
                migrations.AddField(
                    model_name='project',
                    name='estimated_hours',
                    field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
                ),
                migrations.AddField(
                    model_name='project',
                    name='notify_on_phase_change',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='project',
                    name='phase',
                    field=models.CharField(default='planning', max_length=20),
                ),
                migrations.AddField(
                    model_name='project',
                    name='quality_score',
                    field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
                ),
                migrations.AddField(
                    model_name='project',
                    name='risk_level',
                    field=models.CharField(default='low', max_length=20),
                ),
                migrations.AlterField(
                    model_name='project',
                    name='actual_hours',
                    field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
                ),
                migrations.AlterField(
                    model_name='project',
                    name='description',
                    field=models.TextField(blank=True, default=''),
                ),
                migrations.AlterField(
                    model_name='project',
                    name='tags',
                    field=models.CharField(blank=True, default='', max_length=500),
                ),
            ],
        ),
    ]
