# Generated by Django 5.2.6 on 2025-11-18 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0013_client_client_tenant_status_created_and_more"),
        ("project", "0016_add_timestamps_to_remaining_models"),
    ]

    operations = []
