# Generated by Django 5.2.6 on 2026-03-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_project_auto_complete_on_invoice_paid_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='milestone',
                    name='updated_at',
                    field=models.DateTimeField(auto_now=True),
                ),
                migrations.AlterField(
                    model_name='milestone',
                    name='description',
                    field=models.TextField(blank=True, default=''),
                ),
            ],
        ),
    ]
