# Generated by Django 5.2.6 on 2025-11-18 19:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0017_merge_20251118_1204"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="client",
            name="project_cli_tenant__9f3e6f_idx",
        ),
        migrations.RemoveIndex(
            model_name="client",
            name="project_cli_slug_f396ab_idx",
        ),
        migrations.RemoveIndex(
            model_name="client",
            name="project_cli_created_3fc6e3_idx",
        ),
        migrations.RemoveIndex(
            model_name="project",
            name="project_pro_tenant__71cbc6_idx",
        ),
        migrations.RemoveIndex(
            model_name="project",
            name="project_pro_client__83ef32_idx",
        ),
        migrations.RemoveIndex(
            model_name="project",
            name="project_pro_slug_792393_idx",
        ),
        migrations.RemoveIndex(
            model_name="project",
            name="project_pro_created_16407c_idx",
        ),
    ]
