# Generated by Django 5.2.6 on 2025-11-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0018_remove_client_project_cli_tenant__9f3e6f_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USD", "US Dollar ($)"),
                    ("EUR", "Euro (€)"),
                    ("GBP", "British Pound (£)"),
                    ("JPY", "Japanese Yen (¥)"),
                    ("CAD", "Canadian Dollar (C$)"),
                    ("AUD", "Australian Dollar (A$)"),
                    ("CHF", "Swiss Franc (CHF)"),
                    ("CNY", "Chinese Yuan (¥)"),
                    ("INR", "Indian Rupee (₹)"),
                    ("BRL", "Brazilian Real (R$)"),
                    ("ZAR", "South African Rand (R)"),
                    ("KES", "Kenyan Shilling (KSh)"),
                ],
                help_text="Currency for this invoice",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USD", "US Dollar ($)"),
                    ("EUR", "Euro (€)"),
                    ("GBP", "British Pound (£)"),
                    ("JPY", "Japanese Yen (¥)"),
                    ("CAD", "Canadian Dollar (C$)"),
                    ("AUD", "Australian Dollar (A$)"),
                    ("CHF", "Swiss Franc (CHF)"),
                    ("CNY", "Chinese Yuan (¥)"),
                    ("INR", "Indian Rupee (₹)"),
                    ("BRL", "Brazilian Real (R$)"),
                    ("ZAR", "South African Rand (R)"),
                    ("KES", "Kenyan Shilling (KSh)"),
                ],
                help_text="Currency for this payment",
                max_length=3,
                null=True,
            ),
        ),
    ]
