# Generated by Django 5.2.9 on 2026-01-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='token',
            field=models.TextField(unique=True, verbose_name='token'),
        ),
    ]
