# Generated by Django 5.2.9 on 2026-01-04 22:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('identity', '0002_alter_refreshtoken_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('project', 'Project Management'), ('leave', 'Leave Management'), ('crm', 'CRM'), ('finance', 'Finance'), ('admin', 'Administration'), ('custom', 'Custom')], default='custom', max_length=100)),
                ('app_label', models.CharField(default='identity', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'identity_custom_permissions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(help_text='Department name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Department description and responsibilities')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this department is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'identity_departments',
                'ordering': ['tenant', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('document_file', models.FileField(upload_to='employee_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'db_table': 'identity_employee_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('role', models.CharField(default='Employee', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('email_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'identity_invitations',
            },
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_system_group', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'identity_permission_groups',
                'ordering': ['tenant', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('linkedin_profile', models.URLField(blank=True)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('employee_number', models.CharField(blank=True, max_length=50)),
                ('tax_number', models.CharField(blank=True, max_length=50)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='USA', max_length=100)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('medical_aid_provider', models.CharField(blank=True, max_length=100)),
                ('medical_aid_plan', models.CharField(blank=True, max_length=100)),
                ('medical_aid_number', models.CharField(blank=True, max_length=50)),
                ('medical_conditions', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('branch_code', models.CharField(blank=True, max_length=20)),
                ('account_type', models.CharField(blank=True, choices=[('checking', 'Checking'), ('savings', 'Savings')], max_length=20)),
                ('routing_number', models.CharField(blank=True, max_length=20)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'identity_user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserTenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('is_owner', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('Employee', 'Employee'), ('Department Manager', 'Department Manager'), ('HR Manager', 'HR Manager'), ('General Manager', 'General Manager'), ('Tenant Owner', 'Tenant Owner')], default='Employee', help_text='User role within the tenant', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'identity_user_tenants',
            },
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='identity_us_tenant__e1a081_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='tenant',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who originally created this tenant during signup', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted'], name='identity_us_is_dele_10668a_idx'),
        ),
        migrations.AddField(
            model_name='custompermission',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Department manager (typically Department Manager role)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='parent_department',
            field=models.ForeignKey(blank=True, help_text='Parent department for hierarchical structure', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='identity.department'),
        ),
        migrations.AddField(
            model_name='department',
            name='tenant',
            field=models.ForeignKey(help_text='Company/tenant this department belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='identity.tenant'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.tenant'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='custom_permissions',
            field=models.ManyToManyField(blank=True, to='identity.custompermission'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.tenant'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='permission_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertenant',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='identity.department'),
        ),
        migrations.AddField(
            model_name='usertenant',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.tenant'),
        ),
        migrations.AddField(
            model_name='usertenant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='custompermission',
            index=models.Index(fields=['created_by'], name='identity_cu_created_fe3ea6_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['tenant', 'is_active'], name='identity_de_tenant__260984_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['manager'], name='identity_de_manager_eb6cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['parent_department'], name='identity_de_parent__290f33_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['user', '-uploaded_at'], name='identity_em_user_id_fcce63_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['email', 'tenant'], name='identity_in_email_cc0bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['token'], name='identity_in_token_50b356_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['expires_at'], name='identity_in_expires_f614fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='permissiongroup',
            unique_together={('name', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='identity_us_user_id_50ce9c_idx'),
        ),
        migrations.AddIndex(
            model_name='usertenant',
            index=models.Index(fields=['user', 'tenant'], name='identity_us_user_id_83accc_idx'),
        ),
        migrations.AddIndex(
            model_name='usertenant',
            index=models.Index(fields=['is_approved'], name='identity_us_is_appr_1740a7_idx'),
        ),
        migrations.AddIndex(
            model_name='usertenant',
            index=models.Index(fields=['role'], name='identity_us_role_b39c79_idx'),
        ),
    ]
