# Generated by Django 5.2.6 on 2025-11-20 05:37

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual_leave", "Annual Leave"),
                            ("sick_leave", "Sick Leave"),
                            ("personal_leave", "Personal Leave"),
                            ("maternity_leave", "Maternity/Paternity Leave"),
                            ("emergency_leave", "Emergency Leave"),
                            ("unpaid_leave", "Unpaid Leave"),
                        ],
                        help_text="Type of leave being requested",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(help_text="First day of leave")),
                ("end_date", models.DateField(help_text="Last day of leave")),
                (
                    "days_requested",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Total number of leave days requested",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.5")),
                            django.core.validators.MaxValueValidator(Decimal("365")),
                        ],
                    ),
                ),
                ("reason", models.TextField(blank=True, help_text="Reason for the leave request")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_department_manager", "Pending Department Manager"),
                            ("pending_hr_manager", "Pending HR Manager"),
                            ("pending_general_manager", "Pending General Manager"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("taken", "Leave Taken"),
                        ],
                        db_index=True,
                        default="pending_department_manager",
                        help_text="Current status of leave request",
                        max_length=30,
                    ),
                ),
                (
                    "applied_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the leave request was submitted"
                    ),
                ),
                (
                    "approved_date",
                    models.DateTimeField(
                        blank=True, help_text="When the request was approved/rejected", null=True
                    ),
                ),
                ("approval_notes", models.TextField(blank=True, help_text="Notes from approver")),
                (
                    "current_approval_level",
                    models.CharField(
                        choices=[
                            ("department_manager", "Department Manager"),
                            ("hr_manager", "HR Manager"),
                            ("general_manager", "General Manager"),
                        ],
                        default="department_manager",
                        help_text="Current approval level in workflow",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Manager who approved/rejected the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee requesting leave",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "final_approver",
                    models.ForeignKey(
                        blank=True,
                        help_text="Final approver who completed the workflow",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="final_approved_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Company/tenant the request belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_date"],
            },
        ),
        migrations.CreateModel(
            name="LeaveApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                (
                    "approval_level",
                    models.CharField(
                        choices=[
                            ("department_manager", "Department Manager"),
                            ("hr_manager", "HR Manager"),
                            ("general_manager", "General Manager"),
                        ],
                        help_text="Approval level in the workflow",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Status of this approval step",
                        max_length=20,
                    ),
                ),
                (
                    "approved_date",
                    models.DateTimeField(
                        blank=True, help_text="When this approval step was completed", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Notes or comments from approver"),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="Order in approval sequence (1=first, 2=second, 3=final)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver",
                    models.ForeignKey(
                        help_text="User who performed this approval step",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_request",
                    models.ForeignKey(
                        help_text="Leave request being approved",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="leave_management.leaverequest",
                    ),
                ),
            ],
            options={
                "ordering": ["leave_request", "order"],
            },
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual_leave", "Annual Leave"),
                            ("sick_leave", "Sick Leave"),
                            ("personal_leave", "Personal Leave"),
                            ("maternity_leave", "Maternity/Paternity Leave"),
                            ("emergency_leave", "Emergency Leave"),
                            ("unpaid_leave", "Unpaid Leave"),
                        ],
                        help_text="Type of leave this balance applies to",
                        max_length=20,
                    ),
                ),
                ("year", models.IntegerField(help_text="Calendar year for this leave balance")),
                (
                    "total_days",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Total leave days allocated for this year",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "used_days",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        help_text="Days already used this year",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "carried_over",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        help_text="Days carried over from previous year",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee whose leave balance this represents",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Company/tenant the balance belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "leave_type"],
                "indexes": [
                    models.Index(fields=["tenant", "year"], name="leave_manag_tenant__13d2d9_idx"),
                    models.Index(
                        fields=["employee", "year"], name="leave_manag_employe_f70801_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "used_days__lte",
                                django.db.models.expressions.CombinedExpression(
                                    models.F("total_days"), "+", models.F("carried_over")
                                ),
                            )
                        ),
                        name="leave_balance_used_within_total",
                    )
                ],
                "unique_together": {("employee", "leave_type", "year")},
            },
        ),
        migrations.CreateModel(
            name="LeavePolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual_leave", "Annual Leave"),
                            ("sick_leave", "Sick Leave"),
                            ("personal_leave", "Personal Leave"),
                            ("maternity_leave", "Maternity/Paternity Leave"),
                            ("emergency_leave", "Emergency Leave"),
                            ("unpaid_leave", "Unpaid Leave"),
                        ],
                        help_text="Type of leave this policy applies to",
                        max_length=20,
                    ),
                ),
                (
                    "annual_entitlement",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Default annual leave entitlement in days",
                        max_digits=4,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "max_consecutive_days",
                    models.IntegerField(
                        default=30,
                        help_text="Maximum consecutive days allowed for this leave type",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                    ),
                ),
                (
                    "notice_period_days",
                    models.IntegerField(
                        default=7,
                        help_text="Minimum notice period required in working days",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "carry_over_allowed",
                    models.BooleanField(
                        default=True,
                        help_text="Whether unused leave can be carried over to next year",
                    ),
                ),
                (
                    "max_carry_over",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Maximum days that can be carried over (null = unlimited)",
                        max_digits=4,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "auto_approve_max_days",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Maximum days that can be auto-approved (null = no auto-approval)",
                        max_digits=3,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this policy is currently active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Company/tenant this policy applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_policies",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["leave_type"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "is_active"], name="leave_manag_tenant__6a83c6_idx"
                    )
                ],
                "unique_together": {("tenant", "leave_type")},
            },
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(fields=["tenant", "status"], name="leave_manag_tenant__ced5b4_idx"),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["employee", "status"], name="leave_manag_employe_76bff2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["start_date", "end_date"], name="leave_manag_start_d_903b4d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="leaverequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_date__lte", models.F("end_date"))),
                name="leave_request_start_before_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="leaverequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("days_requested__gt", 0)), name="leave_request_positive_days"
            ),
        ),
        migrations.AddIndex(
            model_name="leaveapproval",
            index=models.Index(
                fields=["leave_request", "status"], name="leave_manag_leave_r_3b480f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaveapproval",
            index=models.Index(fields=["approver"], name="leave_manag_approve_32cdc1_idx"),
        ),
        migrations.AddIndex(
            model_name="leaveapproval",
            index=models.Index(
                fields=["approval_level", "status"], name="leave_manag_approva_36bf34_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leaveapproval",
            unique_together={("leave_request", "approval_level")},
        ),
    ]
