# Generated by Django 5.2.6 on 2025-11-20 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("leave_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveApprovalWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for the workflow (e.g., 'Standard Approval', 'Executive Approval')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of when to use this workflow"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default workflow for the tenant",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this workflow is available for use"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this workflow",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_leave_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this workflow belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_approval_workflows",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LeaveApprovalStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="Order of this step in the workflow (1, 2, 3...)"
                    ),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("user", "Specific User"),
                            ("permission_group", "Permission Group"),
                            ("role", "By Role"),
                            ("department_manager", "Employee's Department Manager"),
                            ("dynamic_hr", "Dynamic HR Selection"),
                            ("dynamic_gm", "Dynamic General Manager Selection"),
                        ],
                        help_text="How approvers are determined for this step",
                        max_length=20,
                    ),
                ),
                (
                    "required_role",
                    models.CharField(
                        blank=True,
                        help_text="Required user role for approval (for 'role' type)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "max_approvers",
                    models.IntegerField(
                        default=1,
                        help_text="Maximum number of approvers to select (prevents duplicates)",
                    ),
                ),
                (
                    "selection_criteria",
                    models.CharField(
                        choices=[
                            ("first", "First by seniority"),
                            ("random", "Random selection"),
                            ("round_robin", "Round robin"),
                        ],
                        default="first",
                        help_text="How to select approvers when multiple are eligible",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this approval step", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of this approval step"
                    ),
                ),
                (
                    "requires_notes",
                    models.BooleanField(
                        default=False,
                        help_text="Whether approvers must provide notes for this step",
                    ),
                ),
                (
                    "min_days_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum leave days required to trigger this step",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "leave_types",
                    models.JSONField(
                        default=list,
                        help_text="Specific leave types this step applies to (empty = all types)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "permission_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Permission group whose members can approve (for 'permission_group' type)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_approval_steps",
                        to="accounts.permissiongroup",
                    ),
                ),
                (
                    "specific_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific user who must approve (for 'user' type)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_approval_steps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        help_text="Workflow this step belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="leave_management.leaveapprovalworkflow",
                    ),
                ),
            ],
            options={
                "ordering": ["workflow", "order"],
            },
        ),
        migrations.AddField(
            model_name="leavepolicy",
            name="approval_workflow",
            field=models.ForeignKey(
                blank=True,
                help_text="Custom approval workflow for this leave type (null = use default workflow)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leave_policies",
                to="leave_management.leaveapprovalworkflow",
            ),
        ),
        migrations.AddIndex(
            model_name="leaveapprovalworkflow",
            index=models.Index(
                fields=["tenant", "is_default"], name="leave_manag_tenant__59c892_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaveapprovalworkflow",
            index=models.Index(
                fields=["tenant", "is_active"], name="leave_manag_tenant__3c8f50_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leaveapprovalworkflow",
            unique_together={("tenant", "name")},
        ),
        migrations.AddIndex(
            model_name="leaveapprovalstep",
            index=models.Index(fields=["workflow", "order"], name="leave_manag_workflo_ca7055_idx"),
        ),
        migrations.AddIndex(
            model_name="leaveapprovalstep",
            index=models.Index(fields=["approval_type"], name="leave_manag_approva_8c08a6_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="leaveapprovalstep",
            unique_together={("workflow", "order")},
        ),
    ]
