# Generated by Django 5.2.6 on 2025-11-13 19:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='current_approval_level',
            field=models.CharField(choices=[('department_manager', 'Department Manager'), ('hr_manager', 'HR Manager'), ('general_manager', 'General Manager')], default='department_manager', help_text='Current approval level in workflow', max_length=20),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='final_approver',
            field=models.ForeignKey(blank=True, help_text='Final approver who completed the workflow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approved_leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='Notes from approver'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending_department_manager', 'Pending Department Manager'), ('pending_hr_manager', 'Pending HR Manager'), ('pending_general_manager', 'Pending General Manager'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('taken', 'Leave Taken')], db_index=True, default='pending_department_manager', help_text='Current status of leave request', max_length=30),
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('approval_level', models.CharField(choices=[('department_manager', 'Department Manager'), ('hr_manager', 'HR Manager'), ('general_manager', 'General Manager')], help_text='Approval level in the workflow', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Status of this approval step', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, help_text='When this approval step was completed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes or comments from approver')),
                ('order', models.IntegerField(help_text='Order in approval sequence (1=first, 2=second, 3=final)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(help_text='User who performed this approval step', on_delete=django.db.models.deletion.CASCADE, related_name='leave_approvals', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(help_text='Leave request being approved', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='leave_management.leaverequest')),
            ],
            options={
                'ordering': ['leave_request', 'order'],
                'indexes': [models.Index(fields=['leave_request', 'status'], name='leave_manag_leave_r_3b480f_idx'), models.Index(fields=['approver'], name='leave_manag_approve_32cdc1_idx'), models.Index(fields=['approval_level', 'status'], name='leave_manag_approva_36bf34_idx')],
                'unique_together': {('leave_request', 'approval_level')},
            },
        ),
    ]
