# Generated by Django 5.2.6 on 2025-11-21 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leave_management", "0004_fix_leavepolicy_fk"),
    ]

    operations = [
        # Remove the complex workflow models that are no longer needed
        migrations.DeleteModel(
            name="ApprovalLevelConfig",
        ),
        migrations.DeleteModel(
            name="LeaveApprovalStep",
        ),
    ]
