# Generated by Django 5.2.6 on 2025-11-24 11:44

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leave_management", "0011_make_sale_price_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavesale",
            name="days_to_sell",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Number of leave days to sell (set by HR during approval)",
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.5")),
                    django.core.validators.MaxValueValidator(Decimal("365")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="leavesale",
            name="leave_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("annual_leave", "Annual Leave"),
                    ("sick_leave", "Sick Leave"),
                    ("personal_leave", "Personal Leave"),
                    ("maternity_leave", "Maternity/Paternity Leave"),
                    ("emergency_leave", "Emergency Leave"),
                    ("unpaid_leave", "Unpaid Leave"),
                ],
                help_text="Type of leave being sold (set by HR during approval)",
                max_length=20,
                null=True,
            ),
        ),
    ]
