# Generated by Django 5.2.9 on 2026-01-03 18:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(choices=[('user_signup', 'User Signup'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('user_profile_update', 'Profile Update'), ('user_password_change', 'Password Change'), ('invitation_sent', 'Invitation Sent'), ('invitation_confirmed', 'Invitation Confirmed'), ('invitation_used', 'Invitation Used'), ('invitation_cancelled', 'Invitation Cancelled'), ('invitation_expired', 'Invitation Expired'), ('member_approved', 'Member Approved'), ('member_rejected', 'Member Rejected'), ('role_created', 'Role Created'), ('role_updated', 'Role Updated'), ('role_assigned', 'Role Assigned'), ('project_created', 'Project Created'), ('project_updated', 'Project Updated'), ('project_deleted', 'Project Deleted'), ('invoice_created', 'Invoice Created'), ('invoice_paid', 'Invoice Paid'), ('payment_received', 'Payment Received'), ('leave_requested', 'Leave Requested'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('sale_created', 'Sale Created'), ('opportunity_created', 'Opportunity Created'), ('customer_created', 'Customer Created'), ('security_failed_login', 'Failed Login Attempt'), ('security_token_misuse', 'Token Misuse'), ('admin_user_suspended', 'User Suspended'), ('admin_user_activated', 'User Activated')], db_index=True, max_length=50)),
                ('resource_type', models.CharField(choices=[('user', 'User'), ('invitation', 'Invitation'), ('role', 'Role'), ('tenant', 'Tenant'), ('profile', 'User Profile'), ('project', 'Project'), ('invoice', 'Invoice'), ('payment', 'Payment'), ('leave_request', 'Leave Request'), ('customer', 'Customer'), ('opportunity', 'Opportunity'), ('sales_activity', 'Sales Activity')], db_index=True, max_length=50)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant_id', 'timestamp'], name='audit_audit_tenant__7e6e1d_idx'), models.Index(fields=['user_id', 'timestamp'], name='audit_audit_user_id_e8be02_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2a3aef_idx')],
            },
        ),
    ]
