# Generated by Django 5.2.9 on 2026-01-03 18:41

import django.core.validators
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('client_id', models.UUIDField(db_index=True)),
                ('project_id', models.UUIDField(blank=True, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='accounting__tenant__209211_idx'), models.Index(fields=['client_id', 'status'], name='accounting__client__ef83c0_idx'), models.Index(fields=['due_date', 'status'], name='accounting__due_dat_cd8de2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('invoice_id', models.UUIDField(blank=True, null=True)),
                ('client_id', models.UUIDField(db_index=True)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cash', 'Cash'), ('check', 'Check'), ('online', 'Online Payment'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('recorded_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-paid_at'],
                'indexes': [models.Index(fields=['tenant_id', 'paid_at'], name='accounting__tenant__8afba0_idx'), models.Index(fields=['invoice_id', 'paid_at'], name='accounting__invoice_079f85_idx'), models.Index(fields=['client_id', 'paid_at'], name='accounting__client__30ab10_idx')],
            },
        ),
    ]
