# Generated by Django 5.2.9 on 2026-01-03 18:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(db_index=True, default='unread', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'user_id', 'status'], name='notificatio_tenant__044386_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_a5f01d_idx'), models.Index(fields=['created_at'], name='notificatio_created_fcd7aa_idx')],
            },
        ),
    ]
