# Generated by Django 5.2.9 on 2026-01-05 15:12

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('prospect', 'Prospect')], db_index=True, default='prospect', max_length=10)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('company_size', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('billing_address', models.TextField(blank=True)),
                ('primary_contact_id', models.UUIDField(blank=True, null=True)),
                ('account_manager_id', models.UUIDField(blank=True, null=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('payment_terms', models.CharField(default='net_30', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='project_cli_tenant__9f3e6f_idx'), models.Index(fields=['slug'], name='project_cli_slug_f396ab_idx'), models.Index(fields=['primary_contact_id'], name='project_cli_primary_6c071f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Milestone', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='planning', max_length=10)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('actual_start', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('project_id', models.UUIDField(db_index=True)),
                ('assignee_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('progress', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='project_mil_tenant__8f4325_idx'), models.Index(fields=['project_id', 'status'], name='project_mil_project_6d22ef_idx'), models.Index(fields=['assignee_id', 'status'], name='project_mil_assigne_764280_idx')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('client_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('archived', 'Archived')], default='planning', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=6)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('progress', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='project_pro_tenant__71cbc6_idx'), models.Index(fields=['client_id', 'created_at'], name='project_pro_client__83ef32_idx'), models.Index(fields=['slug'], name='project_pro_slug_792393_idx')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Task', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('testing', 'Testing'), ('done', 'Done')], db_index=True, default='to_do', max_length=12)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('milestone_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('project_id', models.UUIDField(db_index=True)),
                ('assignee_id', models.UUIDField(blank=True, db_index=True, help_text='UUID of task assignee', null=True)),
                ('assignee_email', models.EmailField(blank=True, help_text='Email of task assignee', max_length=254, null=True)),
                ('assignee_name', models.CharField(blank=True, help_text='Full name of task assignee', max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('estimated_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='project_tas_tenant__9ef753_idx'), models.Index(fields=['project_id', 'status'], name='project_tas_project_4b14b5_idx'), models.Index(fields=['milestone_id', 'status'], name='project_tas_milesto_82d70b_idx'), models.Index(fields=['assignee_id', 'status'], name='project_tas_assigne_550b22_idx')],
            },
        ),
    ]
