# Generated by Django 5.2.9 on 2026-01-04 17:46

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('client_id', models.UUIDField(db_index=True)),
                ('project_id', models.UUIDField(db_index=True)),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_schedule', models.JSONField(default=dict, help_text='Payment milestones and amounts')),
                ('issued_date', models.DateField()),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('approved_by_id', models.UUIDField(blank=True, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Client'), ('signed', 'Signed'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('canceled', 'Canceled')], db_index=True, default='planned', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('milestone_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('progress', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='milestone',
            name='project_mil_tenant__8f4325_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='project_tas_tenant__9ef753_idx',
        ),
        migrations.RenameIndex(
            model_name='milestone',
            new_name='milestone_project_status',
            old_name='project_mil_project_6d22ef_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='task_tenant_assignee_status',
            old_name='project_tas_tenant__6bbf76_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='task_milestone_status',
            old_name='project_tas_milesto_82d70b_idx',
        ),
        migrations.AddField(
            model_name='client',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='last_contact',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='lead_score',
            field=models.IntegerField(default=0, help_text='Lead qualification score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='client',
            name='lead_source',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('referral', 'Referral'), ('social_media', 'Social Media'), ('cold_outreach', 'Cold Outreach'), ('trade_show', 'Trade Show'), ('other', 'Other')], help_text='How did we acquire this client?', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='next_followup',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='satisfaction_score',
            field=models.IntegerField(blank=True, help_text='Client satisfaction rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='milestone',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='actual_hours',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='project',
            name='auto_complete_on_invoice_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='client_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='notify_on_phase_change',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='phase',
            field=models.CharField(choices=[('initiation', 'Initiation'), ('planning', 'Planning'), ('execution', 'Execution'), ('monitoring', 'Monitoring & Control'), ('closure', 'Closure')], default='initiation', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='quality_score',
            field=models.IntegerField(blank=True, help_text='Project quality rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='project',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='sprint_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-1000', '201-1000 employees'), ('1000+', '1000+ employees')], max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='payment_terms',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('net_60', 'Net 60'), ('custom', 'Custom')], default='net_30', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')]),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['created_at'], name='project_cli_created_3fc6e3_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['tenant_id', 'status', 'created_at'], name='milestone_t_status_created'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='project_pro_created_16407c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant_id', 'status', 'created_at'], name='task_tenant_status_created'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['sprint_id', 'status'], name='task_sprint_status'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant_id', 'status'], name='project_con_tenant__bee01a_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['client_id', 'status'], name='project_con_client__df02e5_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_number'], name='project_con_contrac_9c520c_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['created_at'], name='project_con_created_10432d_idx'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['tenant_id', 'status', 'created_at'], name='sprint_tenant_status_created'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['milestone_id', 'status'], name='sprint_milestone_status'),
        ),
    ]
