# Generated by Django 5.2.9 on 2026-01-04 20:43

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('project', '0002_contract_sprint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('tenant_id', models.UUIDField(blank=True, null=True, verbose_name='tenant ID')),
            ],
            options={
                'db_table': 'project_users',
            },
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Sprint',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='project_cli_created_3fc6e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='milestone',
            name='milestone_t_status_created',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='project_pro_created_16407c_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_tenant_status_created',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_sprint_status',
        ),
        migrations.RenameIndex(
            model_name='milestone',
            new_name='project_mil_project_6d22ef_idx',
            old_name='milestone_project_status',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='project_tas_tenant__6bbf76_idx',
            old_name='task_tenant_assignee_status',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='project_tas_milesto_82d70b_idx',
            old_name='task_milestone_status',
        ),
        migrations.RemoveField(
            model_name='client',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_contact',
        ),
        migrations.RemoveField(
            model_name='client',
            name='lead_score',
        ),
        migrations.RemoveField(
            model_name='client',
            name='lead_source',
        ),
        migrations.RemoveField(
            model_name='client',
            name='next_followup',
        ),
        migrations.RemoveField(
            model_name='client',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='client',
            name='satisfaction_score',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='project',
            name='actual_hours',
        ),
        migrations.RemoveField(
            model_name='project',
            name='auto_complete_on_invoice_paid',
        ),
        migrations.RemoveField(
            model_name='project',
            name='client_feedback',
        ),
        migrations.RemoveField(
            model_name='project',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='estimated_hours',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='project',
            name='notify_on_phase_change',
        ),
        migrations.RemoveField(
            model_name='project',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='project',
            name='quality_score',
        ),
        migrations.RemoveField(
            model_name='project',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='task',
            name='sprint_id',
        ),
        migrations.AlterField(
            model_name='client',
            name='company_size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='payment_terms',
            field=models.CharField(default='net_30', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['tenant_id', 'status'], name='project_mil_tenant__8f4325_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant_id', 'status'], name='project_tas_tenant__9ef753_idx'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='project_use_email_b29fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant_id'], name='project_use_tenant__c11da0_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='project_use_is_acti_7b6e18_idx'),
        ),
    ]
