# Generated by Django 5.2.9 on 2026-01-03 18:41

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\\\+?1?\\\\d{9,15}$', 'Enter a valid phone number.')])),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('qualified', 'Qualified Lead'), ('proposal', 'Proposal Sent'), ('negotiation', 'In Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('inactive', 'Inactive')], db_index=True, default='prospect', max_length=20)),
                ('lead_source', models.CharField(blank=True, max_length=50)),
                ('lead_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('company_size', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('primary_contact', models.CharField(blank=True, max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('assigned_to_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('actual_close_date', models.DateField(blank=True, null=True)),
                ('last_contact', models.DateTimeField(blank=True, null=True)),
                ('next_followup', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='sales_custo_tenant__1d22d2_idx'), models.Index(fields=['assigned_to_id', 'status'], name='sales_custo_assigne_644e0f_idx'), models.Index(fields=['lead_score'], name='sales_custo_lead_sc_11d14a_idx'), models.Index(fields=['expected_close_date'], name='sales_custo_expecte_534326_idx'), models.Index(fields=['slug'], name='sales_custo_slug_ba59a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('customer_id', models.UUIDField(db_index=True)),
                ('assigned_to_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('probability', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('stage', models.CharField(choices=[('prospecting', 'Prospecting'), ('qualification', 'Qualification'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], db_index=True, default='prospecting', max_length=20)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('actual_close_date', models.DateField(blank=True, null=True)),
                ('competitors', models.TextField(blank=True)),
                ('competitive_advantage', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('pain_points', models.TextField(blank=True)),
                ('next_steps', models.TextField(blank=True)),
                ('next_followup', models.DateTimeField(blank=True, null=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'stage'], name='sales_oppor_tenant__b2ea1e_idx'), models.Index(fields=['customer_id', 'stage'], name='sales_oppor_custome_f5b17f_idx'), models.Index(fields=['assigned_to_id', 'stage'], name='sales_oppor_assigne_7a9c88_idx'), models.Index(fields=['expected_close_date'], name='sales_oppor_expecte_dc184c_idx'), models.Index(fields=['probability'], name='sales_oppor_probabi_9732d5_idx'), models.Index(fields=['slug'], name='sales_oppor_slug_b4cf8f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalesActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.UUIDField(db_index=True)),
                ('opportunity_id', models.UUIDField(blank=True, null=True)),
                ('performed_by_id', models.UUIDField(blank=True, null=True)),
                ('activity_type', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('demo', 'Product Demo'), ('proposal', 'Proposal Sent'), ('followup', 'Follow-up'), ('negotiation', 'Negotiation'), ('note', 'Internal Note'), ('other', 'Other')], db_index=True, max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True)),
                ('next_action', models.TextField(blank=True)),
                ('next_action_date', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-completed_date', '-scheduled_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'activity_type'], name='sales_sales_tenant__d884ff_idx'), models.Index(fields=['customer_id', 'activity_type'], name='sales_sales_custome_e481d6_idx'), models.Index(fields=['opportunity_id', 'activity_type'], name='sales_sales_opportu_224fa5_idx'), models.Index(fields=['performed_by_id', 'activity_type'], name='sales_sales_perform_9c728b_idx'), models.Index(fields=['scheduled_date'], name='sales_sales_schedul_894278_idx'), models.Index(fields=['completed_date'], name='sales_sales_complet_4b4a53_idx')],
            },
        ),
    ]
