# Generated by Django 5.2.9 on 2026-01-03 18:41

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_request_id', models.UUIDField(db_index=True)),
                ('approver_id', models.UUIDField(db_index=True)),
                ('approval_level', models.CharField(choices=[('department_manager', 'Department Manager'), ('hr_manager', 'HR Manager'), ('general_manager', 'General Manager')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['leave_request_id', 'order'],
                'indexes': [models.Index(fields=['leave_request_id', 'status'], name='hr_leaveapp_leave_r_54a090_idx'), models.Index(fields=['approver_id'], name='hr_leaveapp_approve_348e11_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.UUIDField(db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('leave_type', models.CharField(choices=[('annual_leave', 'Annual Leave'), ('sick_leave', 'Sick Leave'), ('personal_leave', 'Personal Leave'), ('maternity_leave', 'Maternity/Paternity Leave'), ('emergency_leave', 'Emergency Leave'), ('unpaid_leave', 'Unpaid Leave')], max_length=20)),
                ('year', models.IntegerField()),
                ('total_days', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('used_days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('carried_over', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', 'leave_type'],
                'indexes': [models.Index(fields=['tenant_id', 'year'], name='hr_leavebal_tenant__9c442c_idx'), models.Index(fields=['employee_id', 'year'], name='hr_leavebal_employe_38d436_idx')],
                'unique_together': {('employee_id', 'leave_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.UUIDField(db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('leave_type', models.CharField(choices=[('annual_leave', 'Annual Leave'), ('sick_leave', 'Sick Leave'), ('personal_leave', 'Personal Leave'), ('maternity_leave', 'Maternity/Paternity Leave'), ('emergency_leave', 'Emergency Leave'), ('unpaid_leave', 'Unpaid Leave')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_requested', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('365'))])),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_department_manager', 'Pending Department Manager'), ('pending_hr_manager', 'Pending HR Manager'), ('pending_general_manager', 'Pending General Manager'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('taken', 'Leave Taken')], default='pending_department_manager', max_length=30)),
                ('current_approval_level', models.CharField(choices=[('department_manager', 'Department Manager'), ('hr_manager', 'HR Manager'), ('general_manager', 'General Manager')], default='department_manager', max_length=20)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-applied_date'],
                'indexes': [models.Index(fields=['employee_id', 'status'], name='hr_leavereq_employe_1b7929_idx'), models.Index(fields=['tenant_id', 'status'], name='hr_leavereq_tenant__94948b_idx'), models.Index(fields=['start_date', 'end_date'], name='hr_leavereq_start_d_9e9e54_idx'), models.Index(fields=['status', 'current_approval_level'], name='hr_leavereq_status_c92169_idx')],
            },
        ),
    ]
